### ISSUE TITLE
invalid api key

### ISSUE THREAD

**Issue by scholtz** [deflex-fi/deflex-sdk-js#2]
Hi, with request

```
https://api.deflex.fi/api/fetchQuote?chain=mainnet&algodUri=https%3A%2F%2Fmainnet-api.algonode.cloud&algodToken=&algodPort=443&fromASAID=0&toASAID=452399768&atomicOnly=true&amount=100000000&type=fixed-input&disabledProtocols=&referrerAddress=AWALLETCPHQPJGCZ6AHLIFPHWBHUEHQ7VBYJVVGQRRY4MEIGWUBKCQYP4Y
```

i am getting now response invalid api key

has something changed? it was working before

**Comment by PhilGabardo** [comment]
Hey - we no longer accept requests anonymously, since some people were hammering the server and incurring a ton of expenses. Please tell me about your use case and how many requests you'll be sending. If it is a trading bot, we won't be able to help you unless you pay a monthly fee.

**Comment by scholtz** [comment]
I have implemented it it in AWallet - https://www.a-wallet.net/ 

https://forum.algorand.org/t/algorand-wallet-open-source/3497

https://github.com/scholtz/wallet/blob/9aeb06a3f1b1924c8b807b0725ef8402032a4443/src/pages/Swap.vue#L356

https://www.reddit.com/r/AlgorandOfficial/comments/16zp1yh/ama_awallet_open_source_community_wallet/

**Comment by robertflan** [comment]
Hi Philip,
I am facing same issue. Can you help me to fix this issue? Thank you

**Comment by PhilGabardo** [comment]
Hey - we no longer accept requests anonymously, since some people were hammering the server and incurring a ton of expenses. Please tell me about your use case and how many requests you'll be sending. If it is a trading bot, we won't be able to help you unless you pay a monthly fee.

**Comment by robertflan** [comment]
Hi, I used the api_key received from you. but I faced the error when calling this function.
deflex.DeflexOrderRouterClient.fetchTestnetClient(
             uri,
            '',
             '' /* sender.addr */,
           undefined, // referrerAddress
           undefined, // feeBps
           ALGOD_API_KEY
           );
           
           
![error](https://github.com/deflex-fi/deflex-sdk-js/assets/31945936/db07e162-0cf7-47fa-b6ac-81b8906ac26c)

can you help me to fix this issue?
